name: CI/CD Nexus

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ofafakk/projeto-nexus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Baixar CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ·ï¸ Atualizar VersÃ£o no Site
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          sed -i "s/Build: MANUAL/Build: $SHORT_SHA/g" index.html

      - name: ğŸ³ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸš€ Build e Enviar Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest